### ISSUE TITLE
Invalid Layer NeuralTensorLayer

### ISSUE THREAD

**Issue by maximus009** [dapurv5/keras-neural-tensor-layer#3]
Hi,

I am aware that this is a common issue in Keras to not be able to load custom layers.
Were you able to find a fix for this?

Please let me know how we can rectify this issue.

Thanks in advance.

**Comment by maximus009** [comment]
Solved it by saving the weights of the model; and during inference time/testing, re-created the model and loaded the weights again.

**Comment by ophiry** [comment]
a simpler approach is to use the custom_objects parameter in load model

`model = keras.models.load_model(model_full_file_name, custom_objects={ 'NeuralTensorLayer': NeuralTensorLayer})`
